version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: hello_django_db
    environment:
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_pass
      POSTGRES_DB: hello_django_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django_user -d hello_django_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
